# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Publish.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_publish(object):
    def setupUi(self, publish):
        publish.setObjectName("publish")
        publish.resize(568, 348)
        publish.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(publish)
        self.gridLayout.setContentsMargins(0, 6, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(publish)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 566, 302))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_publish = QtWidgets.QFormLayout()
        self.formLayout_publish.setHorizontalSpacing(0)
        self.formLayout_publish.setVerticalSpacing(3)
        self.formLayout_publish.setObjectName("formLayout_publish")
        self.gridLayout_3.addLayout(self.formLayout_publish, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_add = QtWidgets.QPushButton(publish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_add.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/images/加.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_6.addWidget(self.pushButton_add)
        self.pushButton_del = QtWidgets.QPushButton(publish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        self.pushButton_del.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_del.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_del.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/images/减号.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_del.setIcon(icon1)
        self.pushButton_del.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_del.setObjectName("pushButton_del")
        self.horizontalLayout_6.addWidget(self.pushButton_del)
        self.checkBox_hex_mul = QtWidgets.QCheckBox(publish)
        self.checkBox_hex_mul.setObjectName("checkBox_hex_mul")
        self.horizontalLayout_6.addWidget(self.checkBox_hex_mul)
        self.checkBox_publish_mul = QtWidgets.QCheckBox(publish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_publish_mul.sizePolicy().hasHeightForWidth())
        self.checkBox_publish_mul.setSizePolicy(sizePolicy)
        self.checkBox_publish_mul.setMinimumSize(QtCore.QSize(30, 30))
        self.checkBox_publish_mul.setMaximumSize(QtCore.QSize(85, 30))
        self.checkBox_publish_mul.setToolTipDuration(0)
        self.checkBox_publish_mul.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_publish_mul.setObjectName("checkBox_publish_mul")
        self.horizontalLayout_6.addWidget(self.checkBox_publish_mul)
        self.label_6 = QtWidgets.QLabel(publish)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_times_mul = QtWidgets.QLineEdit(publish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_times_mul.sizePolicy().hasHeightForWidth())
        self.lineEdit_times_mul.setSizePolicy(sizePolicy)
        self.lineEdit_times_mul.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_times_mul.setObjectName("lineEdit_times_mul")
        self.horizontalLayout_6.addWidget(self.lineEdit_times_mul)
        spacerItem = QtWidgets.QSpacerItem(13, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)

        self.retranslateUi(publish)
        QtCore.QMetaObject.connectSlotsByName(publish)

    def retranslateUi(self, publish):
        _translate = QtCore.QCoreApplication.translate
        publish.setWindowTitle(_translate("publish", "Form"))
        self.pushButton_add.setToolTip(_translate("publish", "添加一行"))
        self.pushButton_del.setToolTip(_translate("publish", "删除最后一行"))
        self.checkBox_hex_mul.setText(_translate("publish", "Hex"))
        self.checkBox_publish_mul.setToolTip(_translate("publish", "<html><head/><body><p>发布数据</p></body></html>"))
        self.checkBox_publish_mul.setStatusTip(_translate("publish", "发布数据"))
        self.checkBox_publish_mul.setWhatsThis(_translate("publish", "发布数据"))
        self.checkBox_publish_mul.setText(_translate("publish", "循环发送"))
        self.label_6.setText(_translate("publish", "间隔:"))
        self.lineEdit_times_mul.setToolTip(_translate("publish", "循环发送间隔"))
        self.lineEdit_times_mul.setPlaceholderText(_translate("publish", "单位: 毫秒"))

import img_rc
