# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SendList.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 353)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Hex = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Hex.setObjectName("checkBox_Hex")
        self.horizontalLayout_2.addWidget(self.checkBox_Hex)
        self.checkBox_Times = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Times.setObjectName("checkBox_Times")
        self.horizontalLayout_2.addWidget(self.checkBox_Times)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_Times = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Times.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_Times.setObjectName("lineEdit_Times")
        self.horizontalLayout_2.addWidget(self.lineEdit_Times)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxs1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs1.setText("")
        self.checkBoxs1.setObjectName("checkBoxs1")
        self.horizontalLayout.addWidget(self.checkBoxs1)
        self.lineEdits1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits1.setObjectName("lineEdits1")
        self.horizontalLayout.addWidget(self.lineEdits1)
        self.pushButtons1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons1.setObjectName("pushButtons1")
        self.horizontalLayout.addWidget(self.pushButtons1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(3)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBoxs2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs2.setText("")
        self.checkBoxs2.setObjectName("checkBoxs2")
        self.horizontalLayout_21.addWidget(self.checkBoxs2)
        self.lineEdits2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits2.setObjectName("lineEdits2")
        self.horizontalLayout_21.addWidget(self.lineEdits2)
        self.pushButtons2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons2.setObjectName("pushButtons2")
        self.horizontalLayout_21.addWidget(self.pushButtons2)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(3)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBoxs3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs3.setText("")
        self.checkBoxs3.setObjectName("checkBoxs3")
        self.horizontalLayout_23.addWidget(self.checkBoxs3)
        self.lineEdits3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits3.setObjectName("lineEdits3")
        self.horizontalLayout_23.addWidget(self.lineEdits3)
        self.pushButtons3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons3.setObjectName("pushButtons3")
        self.horizontalLayout_23.addWidget(self.pushButtons3)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(3)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.checkBoxs4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs4.setText("")
        self.checkBoxs4.setObjectName("checkBoxs4")
        self.horizontalLayout_22.addWidget(self.checkBoxs4)
        self.lineEdits4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits4.setObjectName("lineEdits4")
        self.horizontalLayout_22.addWidget(self.lineEdits4)
        self.pushButtons4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons4.setObjectName("pushButtons4")
        self.horizontalLayout_22.addWidget(self.pushButtons4)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(3)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkBoxs5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs5.setText("")
        self.checkBoxs5.setObjectName("checkBoxs5")
        self.horizontalLayout_25.addWidget(self.checkBoxs5)
        self.lineEdits5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits5.setObjectName("lineEdits5")
        self.horizontalLayout_25.addWidget(self.lineEdits5)
        self.pushButtons5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons5.setObjectName("pushButtons5")
        self.horizontalLayout_25.addWidget(self.pushButtons5)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(3)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.checkBoxs6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs6.setText("")
        self.checkBoxs6.setObjectName("checkBoxs6")
        self.horizontalLayout_26.addWidget(self.checkBoxs6)
        self.lineEdits6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits6.setObjectName("lineEdits6")
        self.horizontalLayout_26.addWidget(self.lineEdits6)
        self.pushButtons6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons6.setObjectName("pushButtons6")
        self.horizontalLayout_26.addWidget(self.pushButtons6)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(3)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.checkBoxs7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs7.setText("")
        self.checkBoxs7.setObjectName("checkBoxs7")
        self.horizontalLayout_27.addWidget(self.checkBoxs7)
        self.lineEdits7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits7.setObjectName("lineEdits7")
        self.horizontalLayout_27.addWidget(self.lineEdits7)
        self.pushButtons7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons7.setObjectName("pushButtons7")
        self.horizontalLayout_27.addWidget(self.pushButtons7)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(3)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.checkBoxss8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxss8.setText("")
        self.checkBoxss8.setObjectName("checkBoxss8")
        self.horizontalLayout_28.addWidget(self.checkBoxss8)
        self.lineEdits8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits8.setObjectName("lineEdits8")
        self.horizontalLayout_28.addWidget(self.lineEdits8)
        self.pushButtons8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons8.setObjectName("pushButtons8")
        self.horizontalLayout_28.addWidget(self.pushButtons8)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(3)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.checkBoxs9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs9.setText("")
        self.checkBoxs9.setObjectName("checkBoxs9")
        self.horizontalLayout_29.addWidget(self.checkBoxs9)
        self.lineEdits9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits9.setObjectName("lineEdits9")
        self.horizontalLayout_29.addWidget(self.lineEdits9)
        self.pushButtons9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons9.setObjectName("pushButtons9")
        self.horizontalLayout_29.addWidget(self.pushButtons9)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setSpacing(3)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.checkBoxs10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs10.setText("")
        self.checkBoxs10.setObjectName("checkBoxs10")
        self.horizontalLayout_30.addWidget(self.checkBoxs10)
        self.lineEdits10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits10.setObjectName("lineEdits10")
        self.horizontalLayout_30.addWidget(self.lineEdits10)
        self.pushButtons10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons10.setObjectName("pushButtons10")
        self.horizontalLayout_30.addWidget(self.pushButtons10)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setSpacing(3)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.checkBoxs11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs11.setText("")
        self.checkBoxs11.setObjectName("checkBoxs11")
        self.horizontalLayout_31.addWidget(self.checkBoxs11)
        self.lineEdits11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits11.setObjectName("lineEdits11")
        self.horizontalLayout_31.addWidget(self.lineEdits11)
        self.pushButtons11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons11.setObjectName("pushButtons11")
        self.horizontalLayout_31.addWidget(self.pushButtons11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setSpacing(3)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.checkBoxs12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs12.setText("")
        self.checkBoxs12.setObjectName("checkBoxs12")
        self.horizontalLayout_32.addWidget(self.checkBoxs12)
        self.lineEdits12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits12.setObjectName("lineEdits12")
        self.horizontalLayout_32.addWidget(self.lineEdits12)
        self.pushButtons12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons12.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons12.setObjectName("pushButtons12")
        self.horizontalLayout_32.addWidget(self.pushButtons12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setSpacing(3)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.checkBoxs13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs13.setText("")
        self.checkBoxs13.setObjectName("checkBoxs13")
        self.horizontalLayout_33.addWidget(self.checkBoxs13)
        self.lineEdits13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits13.setObjectName("lineEdits13")
        self.horizontalLayout_33.addWidget(self.lineEdits13)
        self.pushButtons13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons13.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons13.setObjectName("pushButtons13")
        self.horizontalLayout_33.addWidget(self.pushButtons13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSpacing(3)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.checkBoxs14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs14.setText("")
        self.checkBoxs14.setObjectName("checkBoxs14")
        self.horizontalLayout_34.addWidget(self.checkBoxs14)
        self.lineEdits14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits14.setObjectName("lineEdits14")
        self.horizontalLayout_34.addWidget(self.lineEdits14)
        self.pushButtons14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons14.setObjectName("pushButtons14")
        self.horizontalLayout_34.addWidget(self.pushButtons14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setSpacing(3)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.checkBoxs15 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs15.setText("")
        self.checkBoxs15.setObjectName("checkBoxs15")
        self.horizontalLayout_35.addWidget(self.checkBoxs15)
        self.lineEdits15 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits15.setObjectName("lineEdits15")
        self.horizontalLayout_35.addWidget(self.lineEdits15)
        self.pushButtons15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons15.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons15.setObjectName("pushButtons15")
        self.horizontalLayout_35.addWidget(self.pushButtons15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setSpacing(3)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.checkBoxs16 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs16.setText("")
        self.checkBoxs16.setObjectName("checkBoxs16")
        self.horizontalLayout_36.addWidget(self.checkBoxs16)
        self.lineEdits16 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits16.setObjectName("lineEdits16")
        self.horizontalLayout_36.addWidget(self.lineEdits16)
        self.pushButtons16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons16.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons16.setObjectName("pushButtons16")
        self.horizontalLayout_36.addWidget(self.pushButtons16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setSpacing(3)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.checkBoxs17 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs17.setText("")
        self.checkBoxs17.setObjectName("checkBoxs17")
        self.horizontalLayout_37.addWidget(self.checkBoxs17)
        self.lineEdits17 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits17.setObjectName("lineEdits17")
        self.horizontalLayout_37.addWidget(self.lineEdits17)
        self.pushButtons17 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons17.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons17.setObjectName("pushButtons17")
        self.horizontalLayout_37.addWidget(self.pushButtons17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSpacing(3)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.checkBoxs18 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs18.setText("")
        self.checkBoxs18.setObjectName("checkBoxs18")
        self.horizontalLayout_38.addWidget(self.checkBoxs18)
        self.lineEdits18 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits18.setObjectName("lineEdits18")
        self.horizontalLayout_38.addWidget(self.lineEdits18)
        self.pushButtons18 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons18.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons18.setObjectName("pushButtons18")
        self.horizontalLayout_38.addWidget(self.pushButtons18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setSpacing(3)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.checkBoxs19 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs19.setText("")
        self.checkBoxs19.setObjectName("checkBoxs19")
        self.horizontalLayout_39.addWidget(self.checkBoxs19)
        self.lineEdits19 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits19.setObjectName("lineEdits19")
        self.horizontalLayout_39.addWidget(self.lineEdits19)
        self.pushButtons19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons19.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons19.setObjectName("pushButtons19")
        self.horizontalLayout_39.addWidget(self.pushButtons19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(3)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.checkBoxs20 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxs20.setText("")
        self.checkBoxs20.setObjectName("checkBoxs20")
        self.horizontalLayout_40.addWidget(self.checkBoxs20)
        self.lineEdits20 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdits20.setObjectName("lineEdits20")
        self.horizontalLayout_40.addWidget(self.lineEdits20)
        self.pushButtons20 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtons20.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtons20.setObjectName("pushButtons20")
        self.horizontalLayout_40.addWidget(self.pushButtons20)
        self.verticalLayout_3.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "发送列表"))
        self.checkBox_Hex.setText(_translate("Form", "十六进制发送"))
        self.checkBox_Times.setText(_translate("Form", "循环发送"))
        self.label.setText(_translate("Form", "循环间隔"))
        self.label_2.setText(_translate("Form", "毫秒"))
        self.pushButtons1.setText(_translate("Form", "1"))
        self.pushButtons2.setText(_translate("Form", "2"))
        self.pushButtons3.setText(_translate("Form", "3"))
        self.pushButtons4.setText(_translate("Form", "4"))
        self.pushButtons5.setText(_translate("Form", "5"))
        self.pushButtons6.setText(_translate("Form", "6"))
        self.pushButtons7.setText(_translate("Form", "7"))
        self.pushButtons8.setText(_translate("Form", "8"))
        self.pushButtons9.setText(_translate("Form", "9"))
        self.pushButtons10.setText(_translate("Form", "10"))
        self.pushButtons11.setText(_translate("Form", "11"))
        self.pushButtons12.setText(_translate("Form", "12"))
        self.pushButtons13.setText(_translate("Form", "13"))
        self.pushButtons14.setText(_translate("Form", "14"))
        self.pushButtons15.setText(_translate("Form", "15"))
        self.pushButtons16.setText(_translate("Form", "16"))
        self.pushButtons17.setText(_translate("Form", "17"))
        self.pushButtons18.setText(_translate("Form", "18"))
        self.pushButtons19.setText(_translate("Form", "19"))
        self.pushButtons20.setText(_translate("Form", "20"))

