# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCPServer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 459)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMaximumSize(QtCore.QSize(137, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.verticalLayout.addWidget(self.lineEdit_IP)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_Port = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.verticalLayout.addWidget(self.lineEdit_Port)
        self.checkBox_Display_Time = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Display_Time.setObjectName("checkBox_Display_Time")
        self.verticalLayout.addWidget(self.checkBox_Display_Time)
        self.checkBox_Display_Hex = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Display_Hex.setObjectName("checkBox_Display_Hex")
        self.verticalLayout.addWidget(self.checkBox_Display_Hex)
        self.checkBox_Pause_Display = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Pause_Display.setObjectName("checkBox_Pause_Display")
        self.verticalLayout.addWidget(self.checkBox_Pause_Display)
        self.checkBox_Recv_To_File = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_Recv_To_File.setObjectName("checkBox_Recv_To_File")
        self.verticalLayout.addWidget(self.checkBox_Recv_To_File)
        self.lineEdit_Recv_File_Path = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Recv_File_Path.setObjectName("lineEdit_Recv_File_Path")
        self.verticalLayout.addWidget(self.lineEdit_Recv_File_Path)
        self.pushButton_Connect = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.verticalLayout.addWidget(self.pushButton_Connect)
        self.pushButton_Clear_Recv = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Clear_Recv.setObjectName("pushButton_Clear_Recv")
        self.verticalLayout.addWidget(self.pushButton_Clear_Recv)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMaximumSize(QtCore.QSize(137, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_Input_Hex = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Input_Hex.setObjectName("checkBox_Input_Hex")
        self.verticalLayout_2.addWidget(self.checkBox_Input_Hex)
        self.checkBox_Times_Send = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Times_Send.setObjectName("checkBox_Times_Send")
        self.verticalLayout_2.addWidget(self.checkBox_Times_Send)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_Times = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Times.setObjectName("lineEdit_Times")
        self.horizontalLayout.addWidget(self.lineEdit_Times)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_Scan_File = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Scan_File.setObjectName("pushButton_Scan_File")
        self.verticalLayout_2.addWidget(self.pushButton_Scan_File)
        self.lineEdit_Input_File_Path = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_Input_File_Path.setObjectName("lineEdit_Input_File_Path")
        self.verticalLayout_2.addWidget(self.lineEdit_Input_File_Path)
        self.pushButton_Send_Data = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Send_Data.setObjectName("pushButton_Send_Data")
        self.verticalLayout_2.addWidget(self.pushButton_Send_Data)
        self.pushButton_Clear_Input = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Clear_Input.setObjectName("pushButton_Clear_Input")
        self.verticalLayout_2.addWidget(self.pushButton_Clear_Input)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 5, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TCP/IP_Server"))
        self.groupBox_2.setTitle(_translate("Form", "服务器设置"))
        self.label.setText(_translate("Form", "本机IP地址:"))
        self.label_2.setText(_translate("Form", "本地端口:"))
        self.checkBox_Display_Time.setText(_translate("Form", "显示接收时间"))
        self.checkBox_Display_Hex.setText(_translate("Form", "十六进制显示"))
        self.checkBox_Pause_Display.setText(_translate("Form", "暂停接收显示"))
        self.checkBox_Recv_To_File.setText(_translate("Form", "接收转向文件"))
        self.pushButton_Connect.setText(_translate("Form", "连接"))
        self.pushButton_Clear_Recv.setText(_translate("Form", "清空显示"))
        self.groupBox_3.setTitle(_translate("Form", "发送区"))
        self.checkBox_Input_Hex.setText(_translate("Form", "十六进制发送"))
        self.checkBox_Times_Send.setText(_translate("Form", "循环发送"))
        self.label_3.setText(_translate("Form", "发送间隔:"))
        self.label_4.setText(_translate("Form", "毫秒"))
        self.pushButton_Scan_File.setText(_translate("Form", "浏览文件"))
        self.pushButton_Send_Data.setText(_translate("Form", "发送"))
        self.pushButton_Clear_Input.setText(_translate("Form", "清空显示"))
        self.groupBox.setTitle(_translate("Form", "网络数据接收"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))

