# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TCPClients.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 477)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_set = QtWidgets.QWidget()
        self.tab_set.setObjectName("tab_set")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_set)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab_set)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(140, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_IP = QtWidgets.QLineEdit(self.tab_set)
        self.lineEdit_IP.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.verticalLayout.addWidget(self.lineEdit_IP)
        self.lineEdit_Port = QtWidgets.QLineEdit(self.tab_set)
        self.lineEdit_Port.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.verticalLayout.addWidget(self.lineEdit_Port)
        self.lineEdit_Clients_Count = QtWidgets.QLineEdit(self.tab_set)
        self.lineEdit_Clients_Count.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_Clients_Count.setObjectName("lineEdit_Clients_Count")
        self.verticalLayout.addWidget(self.lineEdit_Clients_Count)
        self.pushButton_Connect = QtWidgets.QPushButton(self.tab_set)
        self.pushButton_Connect.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.verticalLayout.addWidget(self.pushButton_Connect)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_set, "")
        self.tab_single = QtWidgets.QWidget()
        self.tab_single.setObjectName("tab_single")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_single)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_single)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_3.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_single)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.checkBox = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_single)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.label = QtWidgets.QLabel(self.tab_single)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_single)
        self.lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.tab_single)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_single, "")
        self.tab_mul = QtWidgets.QWidget()
        self.tab_mul.setObjectName("tab_mul")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_mul)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_mul)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 546, 135))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_publish = QtWidgets.QFormLayout()
        self.formLayout_publish.setHorizontalSpacing(0)
        self.formLayout_publish.setVerticalSpacing(3)
        self.formLayout_publish.setObjectName("formLayout_publish")
        self.gridLayout_4.addLayout(self.formLayout_publish, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_mul)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/加.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_mul)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_8.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/减号.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.checkBox_publish = QtWidgets.QCheckBox(self.tab_mul)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_publish.sizePolicy().hasHeightForWidth())
        self.checkBox_publish.setSizePolicy(sizePolicy)
        self.checkBox_publish.setMinimumSize(QtCore.QSize(30, 30))
        self.checkBox_publish.setMaximumSize(QtCore.QSize(10000, 30))
        self.checkBox_publish.setToolTipDuration(0)
        self.checkBox_publish.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_publish.setObjectName("checkBox_publish")
        self.horizontalLayout_7.addWidget(self.checkBox_publish)
        self.lineEdit_times = QtWidgets.QLineEdit(self.tab_mul)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_times.sizePolicy().hasHeightForWidth())
        self.lineEdit_times.setSizePolicy(sizePolicy)
        self.lineEdit_times.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.horizontalLayout_7.addWidget(self.lineEdit_times)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.tab_mul)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_counts = QtWidgets.QLabel(self.tab_mul)
        self.label_counts.setMinimumSize(QtCore.QSize(50, 0))
        self.label_counts.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_counts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_counts.setObjectName("label_counts")
        self.horizontalLayout_7.addWidget(self.label_counts)
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_mul)
        self.pushButton_clear.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_7.addWidget(self.pushButton_clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_mul, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_Display_Time = QtWidgets.QCheckBox(Form)
        self.checkBox_Display_Time.setObjectName("checkBox_Display_Time")
        self.horizontalLayout_4.addWidget(self.checkBox_Display_Time)
        self.checkBox_Display_Hex = QtWidgets.QCheckBox(Form)
        self.checkBox_Display_Hex.setObjectName("checkBox_Display_Hex")
        self.horizontalLayout_4.addWidget(self.checkBox_Display_Hex)
        self.checkBox_Pause = QtWidgets.QCheckBox(Form)
        self.checkBox_Pause.setObjectName("checkBox_Pause")
        self.horizontalLayout_4.addWidget(self.checkBox_Pause)
        self.pushButton_Clear_Display = QtWidgets.QPushButton(Form)
        self.pushButton_Clear_Display.setObjectName("pushButton_Clear_Display")
        self.horizontalLayout_4.addWidget(self.pushButton_Clear_Display)
        self.pushButton_Clear_Count = QtWidgets.QPushButton(Form)
        self.pushButton_Clear_Count.setObjectName("pushButton_Clear_Count")
        self.horizontalLayout_4.addWidget(self.pushButton_Clear_Count)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_RX = QtWidgets.QLabel(Form)
        self.label_RX.setMinimumSize(QtCore.QSize(40, 0))
        self.label_RX.setObjectName("label_RX")
        self.horizontalLayout.addWidget(self.label_RX)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_TX = QtWidgets.QLabel(Form)
        self.label_TX.setMinimumSize(QtCore.QSize(40, 0))
        self.label_TX.setObjectName("label_TX")
        self.horizontalLayout_2.addWidget(self.label_TX)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TCP/IP_Clients"))
        self.textEdit.setPlaceholderText(_translate("Form", "网络数据接收"))
        self.listWidget.setToolTip(_translate("Form", "客户端列表"))
        self.lineEdit_IP.setPlaceholderText(_translate("Form", "目标服务器地址"))
        self.lineEdit_Port.setPlaceholderText(_translate("Form", "端口号"))
        self.lineEdit_Clients_Count.setPlaceholderText(_translate("Form", "客户端个数"))
        self.pushButton_Connect.setText(_translate("Form", "连接"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_set), _translate("Form", "配置"))
        self.pushButton.setText(_translate("Form", "发送"))
        self.checkBox.setText(_translate("Form", "十六进制"))
        self.checkBox_2.setText(_translate("Form", "循环发送"))
        self.label.setText(_translate("Form", "间隔:"))
        self.label_2.setText(_translate("Form", "ms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_single), _translate("Form", "单客户端"))
        self.pushButton_7.setToolTip(_translate("Form", "添加一行"))
        self.pushButton_8.setToolTip(_translate("Form", "删除最后一行"))
        self.checkBox_publish.setToolTip(_translate("Form", "<html><head/><body><p>发布数据</p></body></html>"))
        self.checkBox_publish.setStatusTip(_translate("Form", "发布数据"))
        self.checkBox_publish.setWhatsThis(_translate("Form", "发布数据"))
        self.checkBox_publish.setText(_translate("Form", "循环发送"))
        self.lineEdit_times.setToolTip(_translate("Form", "循环发送间隔"))
        self.lineEdit_times.setPlaceholderText(_translate("Form", "间隔, 单位: 秒"))
        self.label_4.setText(_translate("Form", "发布的字节数"))
        self.label_counts.setText(_translate("Form", "0"))
        self.pushButton_clear.setText(_translate("Form", "清空计数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mul), _translate("Form", "多客户端"))
        self.checkBox_Display_Time.setText(_translate("Form", "接收时间"))
        self.checkBox_Display_Hex.setText(_translate("Form", "HEX显示"))
        self.checkBox_Pause.setText(_translate("Form", "暂停接收"))
        self.pushButton_Clear_Display.setText(_translate("Form", "清空显示"))
        self.pushButton_Clear_Count.setText(_translate("Form", "清空计数"))
        self.label_3.setText(_translate("Form", "RX"))
        self.label_RX.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "TX"))
        self.label_TX.setText(_translate("Form", "0"))

